// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int32
	AccountID sql.NullInt32
	// can be negative or positive
	Amount    int64
	CreatedAt interface{}
}

type Transfer struct {
	ID            int32
	FromAccountID sql.NullInt32
	ToAccountID   sql.NullInt32
	// must be positive
	Amount    int64
	CreatedAt time.Time
}
